# Unencrypted for local testing
# listener 1883 127.0.0.1

# =================================================================
# Encrypted listener
# =================================================================
listener 8883
protocol mqtt
tls_version tlsv1.2
<<<<<<< Updated upstream
cafile   certs/ca.crt
certfile certs/broker.crt
keyfile  certs/broker.key
=======
cafile   ./certs/ca.crt
certfile ./certs/broker.crt
keyfile  ./certs/broker.key
>>>>>>> Stashed changes
require_certificate true
use_identity_as_username true
allow_anonymous false

# =================================================================
# Encrypted listener for ESP devices
# =================================================================
listener 8885
protocol mqtt
tls_version tlsv1.2
<<<<<<< Updated upstream
cafile   esp_certs/ca.crt
certfile esp_certs/broker.crt
keyfile  esp_certs/broker.key
=======
cafile   ./esp_certs/ca.crt
certfile ./esp_certs/broker.crt
keyfile  ./esp_certs/broker.key
>>>>>>> Stashed changes
require_certificate true
use_identity_as_username true
allow_anonymous false
