# For testing
# listener 1883 0.0.0.0
# allow_anonymous true
# protocol mqtt


listener 8883
cafile   C:/path/to/certs/ca.crt
certfile C:/path/to/certs/broker.crt
keyfile  C:/path/to/certs/broker.key
require_certificate true   
use_identity_as_username true
allow_anonymous false